version: '3.9'

services:
  gitlab:
    image: gitlab/gitlab-ce:13.2.9-ce.0
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 22:22/tcp
    environment:
      GITLAB_OMNIBUS_CONFIG: |-
        external_url 'http://gitlab.myvoid.blog'
        gitlab_rails['initial_root_password'] = '********'
