version: '3.9'

services:
  ca:
    image: smallstep/step-ca:0.18.1
    expose:
      - '9000'
    environment:
      DOCKER_STEPCA_INIT_NAME: "${ORG}"
      DOCKER_STEPCA_INIT_DNS_NAMES: 'localhost'
      DOCKER_STEPCA_INIT_PASSWORD: "${CA_PASSWORD}"
    volumes:
      - ./ca/db:/home/step/db:Z
      - ./ca/certs:/home/step/certs:Z
      - ./ca/config:/home/step/config:Z
      - ./ca/secrets:/home/step/secrets:Z
    restart: unless-stopped
  postgres:
    image: postgres:12
    expose:
      - '5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      GITLAB_USER: gitlab
      GITLAB_PASSWORD: "${GITLAB_PASSWORD}"
      GITLAB_DB: gitlabhq_production
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: "${KEYCLOAK_PASSWORD}"
      KEYCLOAK_DB: keycloak
    volumes:
      - ./postgres/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - ./postgres/data:/var/lib/postgresql/data:Z
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
  keycloak:
    image: quay.io/keycloak/keycloak:16.1.0
    expose:
      - '8080'
    environment:
      KEYCLOAK_USER: root
      KEYCLOAK_PASSWORD: "${KEYCLOAK_PASSWORD}"
      PROXY_ADDRESS_FORWARDING: true
      DB_VENDOR: postgres
      DB_USER: keycloak
      DB_PASSWORD: "${KEYCLOAK_PASSWORD}"
      DB_ADDR: postgres
      DB_DATABASE: keycloak
    volumes:
      - ./keycloak/wait-deps-wrapper.sh:/usr/local/bin/wait-deps-wrapper.sh:ro
      - ./keycloak/health-check.sh:/usr/local/bin/health-check.sh:ro
    depends_on:
      - postgres
    entrypoint: ['wait-deps-wrapper.sh', '/opt/jboss/tools/docker-entrypoint.sh', '-b 0.0.0.0']
    healthcheck:
      test: ['CMD-SHELL', 'health-check.sh']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
  gitlab:
    image: gitlab/gitlab-ce:13.2.9-ce.0
    extra_hosts:
    - "${KEYCLOAK_HOST}:${DOCK0_IP}"
    expose:
      - '80'
    ports:
      - 22:22/tcp
    volumes:
      - ./gitlab/wait-deps-wrapper.sh:/usr/local/bin/wait-deps-wrapper.sh:ro
      - ./gitlab/config:/etc/gitlab:Z
      - ./gitlab/data:/var/opt/gitlab:Z
      - ./gitlab/logs:/var/log/gitlab:Z
    environment:
      GITLAB_DATABASE_HOST: postgres
      GITLAB_DATABASE_USERNAME: gitlab
      GITLAB_DATABASE_PASSWORD: "${GITLAB_PASSWORD}"
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://${GITLAB_HOST}"
        gitlab_rails['initial_root_password'] = "${GITLAB_PASSWORD}"
        postgresql['enable'] = false
        gitlab_rails['db_host'] = 'postgres'
        gitlab_rails['db_username'] = 'gitlab'
        gitlab_rails['db_password'] = "${GITLAB_PASSWORD}"
        nginx['redirect_http_to_https'] = false
    depends_on:
      - postgres
    command: ['wait-deps-wrapper.sh', '/assets/wrapper']
    restart: unless-stopped
  nginx:
    image: nginx:1
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      CA_HOST: "${CA_HOST}"
      GITLAB_HOST: "${GITLAB_HOST}"
      KEYCLOAK_HOST: "${KEYCLOAK_HOST}"
    volumes:
      - ./nginx/prepare-wrapper.sh:/usr/local/bin/prepare-wrapper.sh:ro
      - ./nginx/certs:/etc/nginx/certs:Z
      - ./nginx/secrets:/etc/nginx/secrets:Z
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ca.conf:/etc/nginx/conf.d/ca.conf:Z
      - ./nginx/keycloak.conf:/etc/nginx/conf.d/keycloak.conf:Z
      - ./nginx/gitlab.conf:/etc/nginx/conf.d/gitlab.conf:Z
    depends_on:
      - ca
      - keycloak
      - gitlab
    command: ['prepare-wrapper.sh', 'nginx', '-g daemon off;']
    healthcheck:
      test: ['CMD-SHELL', 'service nginx status || exit 1']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
