version: '3.9'

services:
  postgres:
    image: postgres:12
    expose:
      - '5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      GITLAB_USER: gitlab
      GITLAB_PASSWORD: "${GITLAB_PASSWORD}"
      GITLAB_DB: gitlabhq_production
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: "${KEYCLOAK_PASSWORD}"
      KEYCLOAK_DB: keycloak
    volumes:
      - ./postgres/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - ./postgres/data:/var/lib/postgresql/data:Z
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
  gitlab:
    image: gitlab/gitlab-ce:13.2.9-ce.0
    expose:
      - '80'
    ports:
      - 22:22/tcp
    volumes:
      - ./gitlab/wait-deps-wrapper.sh:/usr/local/bin/wait-deps-wrapper.sh:ro
      - ./gitlab/config:/etc/gitlab:Z
      #- ./gitlab/data:/var/opt/gitlab:Z
      #- ./gitlab/logs:/var/log/gitlab:Z
    environment:
      GITLAB_DATABASE_HOST: postgres
      GITLAB_DATABASE_USERNAME: gitlab
      GITLAB_DATABASE_PASSWORD: "${GITLAB_PASSWORD}"
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://${GITLAB_HOST}"
        gitlab_rails['initial_root_password'] = "${GITLAB_PASSWORD}"
        postgresql['enable'] = false
        gitlab_rails['db_host'] = 'postgres'
        gitlab_rails['db_username'] = 'gitlab'
        gitlab_rails['db_password'] = "${GITLAB_PASSWORD}"
        nginx['redirect_http_to_https'] = false
    depends_on:
      - postgres
    command: ['wait-deps-wrapper.sh', '/assets/wrapper']
    restart: unless-stopped
  keycloak:
    image: quay.io/keycloak/keycloak:16.1.0
    expose:
      - '8080'
    environment:
      KEYCLOAK_USER: root
      KEYCLOAK_PASSWORD: "${KEYCLOAK_PASSWORD}"
      DB_VENDOR: postgres
      DB_USER: keycloak
      DB_PASSWORD: "${KEYCLOAK_PASSWORD}"
      DB_ADDR: postgres
      DB_DATABASE: keycloak
    volumes:
      - ./keycloak/wait-deps-wrapper.sh:/usr/local/bin/wait-deps-wrapper.sh:ro
      - ./keycloak/health-check.sh:/usr/local/bin/health-check.sh:ro
    depends_on:
      - postgres
    entrypoint: ['wait-deps-wrapper.sh', '/opt/jboss/tools/docker-entrypoint.sh', '-b 0.0.0.0']
    healthcheck:
      test: ['CMD-SHELL', 'health-check.sh']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
  nginx:
    image: nginx:1
    ports:
      - 80:80/tcp
    volumes:
      - ./nginx/prepare-wrapper.sh:/usr/local/bin/prepare-wrapper.sh:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - gitlab
      - keycloak
    command: ['prepare-wrapper.sh', 'nginx', '-g daemon off;']
    healthcheck:
      test: ['CMD-SHELL', 'health-check.sh']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
